--- 
title: "Trabalho de Conclusão de Curso"
author: "Rafael Felipe Bressan"
date: "`r format(Sys.Date(), format='%d/%m/%Y')`"
output: 
  bookdown::pdf_book:
    template: null
    pandoc_args: --top-level-division=chapter
    includes:
      in_header: preamble.tex
      before_body: beforebody.tex
      #after_body: afterbody.tex
    latex_engine: pdflatex #xelatex
    citation_package: biblatex
    keep_tex: yes
    toc: false
documentclass: abntex2
bibliography: [library.bib]
biblio-style: "abnt"
link-citations: yes
fontsize: 12pt
classoption: 
  - oneside
  - openright
  - a4paper
  - brazil
geometry: 
  - inner=3cm
  - top=3cm
  - outer=2cm
  - bottom=2cm
---

# INTRODUÇÃO

Suponha que se deseja precificar uma opção de compra sobre uma ação, vamos denotar o preço desta _call_ de $f_t$. Sabemos que na data de expiração, $T$, da opção de compra seu preço será: $f_T=max(S_T - K, 0)$, onde $S_T$ é o preço da ação subjacente na data $T$ e $K$ é o preço de exercício da opção. Podemos criar um portfólio que envolva um ativo livre de risco, com preço $B_t$ e a ação objeto do derivativo, $S_t$, que recrie o mesmo valor de pagamento que a opção na data de expiração. Ou seja, criamos o portfólio de replicação $P_t=\Delta S_t + b B_t$, no qual devemos escolher os valores de $\Delta$ e $b$ de tal forma que $f_T = P_T$.

Este portfólio formado pela venda do ativo livre de risco e compra do ativo objeto é denominado **portfólio de replicação**, pois, ele fornece um fluxo de caixa igual ao derivativo que buscamos precificar. Ao adicionarmos ao portfólio de replicação a venda (ou seja, o negativo) do derivativo, temos um portfólio _hedgeado_, onde não existe mais incerteza com relação ao seu retorno esperado.

## PROBLEMA

\begin{equation}
dS_t=\mu S_t+\sigma S_t dW_t 
(\#eq:ds)
\end{equation}

\lipsum[1]

Agora é possível referenciar a equação \@ref(eq:ds) com o comando `\@ref(eq:ds)`.

## JUSTIFICATIVA

Inserir código do R que gere gráficos também é muito simples.

```{r grafico, echo=TRUE, fig.cap="Gráfico gerado pelo R"}
library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

## OBJETIVOS

Link são criados facilmente na escrita com [Markdown](https://daringfireball.net/projects/markdown/syntax#link).

